name: CI (Development)
on:
  push:
    branches-ignore:
      - main
    paths:
      - '.github/workflows/development.continuous-integration.yml'
      - 'package*.json'
      - 'src/**'
jobs:
  quality-control:
    name: 'Quality Control >'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node_version: [12, 14, 16]
        script: ['lint', 'format', 'build', 'test:ci']
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node_version }} environment
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node_version }}
      - name: Install npm dependencies
        run: npm ci
      - name: Run ${{ matrix.script }} on npm package
        run: npm run ${{ matrix.script }}
